![Logo ITQ](./img/logoitqv1.jpg)

Segundo Programa en Python

# Estandarización

![Logo Python](./img/python_logo.png)

* Nombre: *Christian Zumárraga*
* Fecha : **25-09-2026**
* Repositorio: *[Link del repositorio de GitHub](https://github.com/Crishito/machine2/blob/main/Programa2.Estandarizacion.ipynb)*

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# Carga de datos.
X_train = np.array([[ 1., -1., 2.],
                    [ 2., 0., 0.],
                    [ 0., 1., -1.]])

In [3]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [4]:
X_train_2 = np.array([[ 1., -1., 2.],
                        [ 2., 0., 0.],
                        [ 0., 1., -1.]])

In [5]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [8]:
# Comprobar si las matrices estandarizadas son iguales

# Devuelve True si ambas matrices tienen los mismos valores
# np.array_equiv(...) → compara los dos arreglos/matrices.
# X_train_std → matriz estandarizada con fit_transform().
# X_train_2_std → matriz estandarizada usando fit() y luego transform().

print(np.array_equiv(X_train_std, X_train_2_std))

True
